var app = new Vue({
    el: '#jet_lag',
    data() {
        return {
            filterDataShow: [],
            nowDate: ' ', // 当前日期
            tableData: [{
                date: '阿巴丹',
                name: '伊朗',
                time_jetlag: '-4:30'
            }, {
                date: '阿布扎比',
                name: '阿联酋',
                time_jetlag: '-4'
            }, {
                date: '亚丁',
                name: '也门',
                time_jetlag: '-5'
            }, {
                date: '安曼',
                name: '约旦',
                time_jetlag: '-6'
            }, {
                date: '安卡拉',
                name: '土耳其',
                time_jetlag: '-6'
            }, {
                date: '巴格达',
                name: '伊拉克',
                time_jetlag: '-5'
            }, {
                date: '巴库',
                name: '阿塞拜疆',
                time_jetlag: '-6'
            }, {
                date: '斯里巴加湾港',
                name: '文莱',
                time_jetlag: '0'
            }, {
                date: '曼谷',
                name: '泰国',
                time_jetlag: '-1'
            }, {
                date: '贝鲁特',
                name: '黎巴嫩',
                time_jetlag: '-6'
            }, {
                date: '孟买',
                name: '印度',
                time_jetlag: '-2:30'
            }, {
                date: '加尔各答',
                name: '印度',
                time_jetlag: '-2:30'
            }, {
                date: '科伦坡',
                name: '斯里兰卡',
                time_jetlag: '-2:30'
            }, {
                date: '大马士革',
                name: '叙利亚',
                time_jetlag: '-6'
            }, {
                date: '达卡',
                name: '孟加拉',
                time_jetlag: '-2'
            }, {
                date: '雅加达',
                name: '印度尼西亚',
                time_jetlag: '-1'
            }, {
                date: '广州',
                name: '中国',
                time_jetlag: '0'
            }, {
                date: '河内',
                name: '越南',
                time_jetlag: '-1'
            }, {
                date: '香港',
                name: '中国',
                time_jetlag: '0'
            }, {
                date: '伊尔库茨克',
                name: '俄罗斯',
                time_jetlag: '0'
            }, {
                date: '伊斯兰堡',
                name: '巴基斯坦',
                time_jetlag: '-3'
            }, {
                date: '耶路撒冷',
                name: '巴勒斯坦',
                time_jetlag: '-6'
            }, {
                date: '卡拉奇',
                name: '巴基斯坦',
                time_jetlag: '-3'
            }, {
                date: '加德满都',
                name: '尼泊尔',
                time_jetlag: '-2:30'
            }, {
                date: '吉隆坡',
                name: '马来西亚',
                time_jetlag: '0'
            }, {
                date: '科威特',
                name: '科威特',
                time_jetlag: '-5'
            }, {
                date: '京都',
                name: '日本',
                time_jetlag: '+1'
            }, {
                date: '帝力',
                name: '东帝汶',
                time_jetlag: '+1'
            }, {
                date: '澳门',
                name: '中国',
                time_jetlag: '0'
            }, {
                date: '马尼拉',
                name: '菲律宾',
                time_jetlag: '0'
            }, {
                date: '麦加',
                name: '沙特',
                time_jetlag: '-5'
            }, {
                date: '长崎',
                name: '日本',
                time_jetlag: '+1'
            }, {
                date: '新德里',
                name: '印度',
                time_jetlag: '-2:30'
            }, {
                date: '尼古拉耶夫斯克（庙街）',
                name: '俄罗斯',
                time_jetlag: '+1'
            }, {
                date: '鄂木斯克',
                name: '俄罗斯',
                time_jetlag: '-3'
            }, {
                date: '大阪',
                name: '日本',
                time_jetlag: '+1'
            }, {
                date: '金边',
                name: '柬埔寨',
                time_jetlag: '-1'
            }, {
                date: '平壤',
                name: '朝鲜',
                time_jetlag: '+1'
            }, {
                date: '仰光',
                name: '缅甸',
                time_jetlag: '-1:30'
            }, {
                date: '拉瓦尔品第',
                name: '巴基斯坦-3',
                time_jetlag: ''
            }, {
                date: '首尔',
                name: '韩国',
                time_jetlag: '+1'
            }, {
                date: '上海',
                name: '中国',
                time_jetlag: '0'
            }, {
                date: '新加坡',
                name: '新加坡',
                time_jetlag: '0'
            }, {
                date: '台北',
                name: '中国',
                time_jetlag: '0'
            }, {
                date: '德黑兰',
                name: '伊朗',
                time_jetlag: '-4:30'
            }, {
                date: '东京',
                name: '日本',
                time_jetlag: '+1'
            }, {
                date: '乌兰巴托',
                name: '蒙古',
                time_jetlag: '0'
            }, {
                date: '符拉迪沃斯托克（海参崴）',
                name: '俄罗斯',
                time_jetlag: '+2'
            }, {
                date: '横滨',
                name: '日本',
                time_jetlag: '+1'
            }, {
                date: '阿伯丁',
                name: '英国',
                time_jetlag: '-8'
            }, {
                date: '阿姆斯特丹',
                name: '荷兰',
                time_jetlag: '-7'
            }, {
                date: '安特卫普',
                name: '比利时',
                time_jetlag: '-7'
            }, {
                date: '雅典',
                name: '希腊',
                time_jetlag: '-6'
            }, {
                date: '贝尔法斯特',
                name: '英国',
                time_jetlag: '-8'
            }, {
                date: '贝尔格莱德',
                name: '塞尔维亚',
                time_jetlag: '-6'
            }, {
                date: '波德戈里察',
                name: '黑山',
                time_jetlag: '-6'
            }, {
                date: '普里什蒂纳',
                name: '科索沃',
                time_jetlag: '-6'
            }, {
                date: '卢布尔雅那',
                name: '斯洛文尼亚',
                time_jetlag: '-6'
            }, {
                date: '萨格勒布',
                name: '克罗地亚',
                time_jetlag: '-6'
            }, {
                date: '萨拉热窝',
                name: '波黑',
                time_jetlag: '-6'
            }, {
                date: '斯科普里',
                name: '马其顿',
                time_jetlag: '-6'
            }, {
                date: '柏林',
                name: '德国',
                time_jetlag: '-7'
            }, {
                date: '伯明翰',
                name: '英国',
                time_jetlag: '-8'
            }, {
                date: '波恩',
                name: '德国',
                time_jetlag: '-7'
            }, {
                date: '布鲁塞尔',
                name: '比利时',
                time_jetlag: '-7'
            }, {
                date: '布加勒斯特',
                name: '罗马尼亚',
                time_jetlag: '-6'
            }, {
                date: '布达佩斯',
                name: '匈牙利',
                time_jetlag: '-7'
            }, {
                date: '康斯坦萨',
                name: '罗马尼亚',
                time_jetlag: '-6'
            }, {
                date: '哥本哈根',
                name: '丹麦',
                time_jetlag: '-7'
            }, {
                date: '都柏林',
                name: '爱尔兰',
                time_jetlag: '-8'
            }, {
                date: '爱丁堡',
                name: '英国',
                time_jetlag: '-8'
            }, {
                date: '法兰克福',
                name: '德国',
                time_jetlag: '-7'
            }, {
                date: '格但斯克',
                name: '波兰',
                time_jetlag: '-7'
            }, {
                date: '日内瓦',
                name: '瑞士',
                time_jetlag: '-7'
            }, {
                date: '热那亚',
                name: '意大利',
                time_jetlag: '-7'
            }, {
                date: '直布罗陀',
                name: '英国殖民地',
                time_jetlag: '-7'
            }, {
                date: '格拉斯哥',
                name: '英国',
                time_jetlag: '-8'
            }, {
                date: '汉堡',
                name: '德国',
                time_jetlag: '-7'
            }, {
                date: '赫尔辛基',
                name: '芬兰',
                time_jetlag: '-6'
            }, {
                date: '伊斯坦布尔',
                name: '土耳其',
                time_jetlag: '-6'
            }, {
                date: '基辅',
                name: '乌克兰',
                time_jetlag: '-5'
            }, {
                date: '利兹',
                name: '英国',
                time_jetlag: '-8'
            }, {
                date: '莱比锡',
                name: '德国',
                time_jetlag: '-7'
            }, {
                date: '里斯本',
                name: '葡萄牙',
                time_jetlag: '-8'
            }, {
                date: '利物浦',
                name: '英国',
                time_jetlag: '-8'
            }, {
                date: '伦敦',
                name: '英国',
                time_jetlag: '-8'
            }, {
                date: '马德里',
                name: '西班牙',
                time_jetlag: '-7'
            }, {
                date: '曼彻斯特',
                name: '英国',
                time_jetlag: '-8'
            }, {
                date: '马塞',
                name: '法国',
                time_jetlag: '-7'
            }, {
                date: '米兰',
                name: '意大利',
                time_jetlag: '-7'
            }, {
                date: '莫斯科',
                name: '俄罗斯',
                time_jetlag: '-5'
            }, {
                date: '慕尼黑',
                name: '德国',
                time_jetlag: '-7'
            }, {
                date: '摩尔曼斯克',
                name: '俄罗斯',
                time_jetlag: '-5'
            }, {
                date: '敖德萨',
                name: '乌克兰',
                time_jetlag: '-5'
            }, {
                date: '奥斯陆',
                name: '挪威',
                time_jetlag: '-7'
            }, {
                date: '巴黎',
                name: '法国',
                time_jetlag: '-7'
            }, {
                date: '布拉格',
                name: '捷克',
                time_jetlag: '-7'
            }, {
                date: '雷克雅未克',
                name: '冰岛',
                time_jetlag: '-8'
            }, {
                date: '罗马',
                name: '意大利',
                time_jetlag: '-7'
            }, {
                date: '鹿特丹',
                name: '荷兰',
                time_jetlag: '-7'
            }, {
                date: '圣彼得堡',
                name: '俄罗斯',
                time_jetlag: '-5'
            }, {
                date: '索菲亚',
                name: '保加利亚',
                time_jetlag: '-6'
            }, {
                date: '斯德哥尔摩',
                name: '瑞典',
                time_jetlag: '-7'
            }, {
                date: '地拉那',
                name: '阿尔巴尼亚',
                time_jetlag: '-7'
            }, {
                date: '梵蒂冈',
                name: '罗马教廷所在地',
                time_jetlag: '-7'
            }, {
                date: '威尼斯',
                name: '意大利',
                time_jetlag: '-7'
            }, {
                date: '维也纳',
                name: '奥地利',
                time_jetlag: '-7'
            }, {
                date: '华沙',
                name: '波兰',
                time_jetlag: '-7'
            }, {
                date: '苏黎世',
                name: '瑞士',
                time_jetlag: '-7'
            }, {
                date: '安克雷奇',
                name: '美国',
                time_jetlag: '-17'
            }, {
                date: '亚松森',
                name: '巴拉圭',
                time_jetlag: '-12'
            }, {
                date: '亚特兰大',
                name: '美国',
                time_jetlag: '-13'
            }, {
                date: '巴尔的摩',
                name: '美国',
                time_jetlag: '-13'
            }, {
                date: '贝伦',
                name: '巴西',
                time_jetlag: '-11'
            }, {
                date: '波哥大',
                name: '哥伦比亚',
                time_jetlag: '-13'
            }, {
                date: '波士顿',
                name: '美国',
                time_jetlag: '-13'
            }, {
                date: '巴西利亚',
                name: '巴西',
                time_jetlag: '-11'
            }, {
                date: '布宜诺斯艾利斯',
                name: '阿根廷',
                time_jetlag: '-11'
            }, {
                date: '加拉加斯',
                name: '委内瑞拉',
                time_jetlag: '-12'
            }, {
                date: '芝加哥',
                name: '美国',
                time_jetlag: '-14'
            }, {
                date: '丘吉尔港',
                name: '加拿大',
                time_jetlag: '-14'
            }, {
                date: '科隆',
                name: '巴拿马',
                time_jetlag: '-13'
            }, {
                date: '达拉斯',
                name: '美国',
                time_jetlag: '-14'
            }, {
                date: '丹佛',
                name: '美国',
                time_jetlag: '-15'
            }, {
                date: '底特律',
                name: '美国',
                time_jetlag: '-13'
            }, {
                date: '埃德蒙顿',
                name: '加拿大',
                time_jetlag: '-15'
            }, {
                date: '哈瓦那',
                name: '古巴',
                time_jetlag: '-13'
            }, {
                date: '休斯敦',
                name: '美国',
                time_jetlag: '-14'
            }, {
                date: '金斯敦',
                name: '牙买加',
                time_jetlag: '-13'
            }, {
                date: '拉巴斯',
                name: '玻利维亚',
                time_jetlag: '-12'
            }, {
                date: '拉斯韦加斯',
                name: '美国',
                time_jetlag: '-16'
            }, {
                date: '利马',
                name: '秘鲁',
                time_jetlag: '-13'
            }, {
                date: '洛杉矶',
                name: '美国',
                time_jetlag: '-16'
            }, {
                date: '墨西哥城',
                name: '墨西哥',
                time_jetlag: '-14'
            }, {
                date: '迈阿密',
                name: '美国',
                time_jetlag: '-13'
            }, {
                date: '蒙得维的亚',
                name: '乌拉圭',
                time_jetlag: '-11'
            }, {
                date: '蒙特利尔',
                name: '加拿大',
                time_jetlag: '-13'
            }, {
                date: '新奥尔良',
                name: '美国',
                time_jetlag: '-14'
            }, {
                date: '纽约',
                name: '美国',
                time_jetlag: '-3'
            }, {
                date: '渥太华',
                name: '加拿大',
                time_jetlag: '-13'
            }, {
                date: '巴拿马城',
                name: '巴拿马',
                time_jetlag: '-13'
            }, {
                date: '帕拉马里博',
                name: '苏里南',
                time_jetlag: '-11'
            }, {
                date: '费城',
                name: '美国',
                time_jetlag: '-13'
            }, {
                date: '匹兹堡',
                name: '美国',
                time_jetlag: '-13'
            }, {
                date: '西班牙港',
                name: '特立尼达和多巴哥',
                time_jetlag: '-12'
            }, {
                date: '魁北克',
                name: '加拿大',
                time_jetlag: '-13'
            }, {
                date: '里约热内卢',
                name: '巴西',
                time_jetlag: '-11'
            }, {
                date: '圣路易斯',
                name: '美国',
                time_jetlag: '-14'
            }, {
                date: '盐湖城',
                name: '美国',
                time_jetlag: '-15'
            }, {
                date: '圣迭戈',
                name: '美国',
                time_jetlag: '-16'
            }, {
                date: '旧金山（圣佛朗西斯科）',
                name: '美国',
                time_jetlag: '-16'
            }, {
                date: '圣胡安',
                name: '波多黎各',
                time_jetlag: '-12'
            }, {
                date: '圣地亚哥',
                name: '智利',
                time_jetlag: '-12'
            }, {
                date: '西雅图',
                name: '美国',
                time_jetlag: '-16'
            }, {
                date: '多伦多',
                name: '加拿大',
                time_jetlag: '-13'
            }, {
                date: '温哥华',
                name: '加拿大',
                time_jetlag: '-16'
            }, {
                date: '华盛顿',
                name: '美国',
                time_jetlag: '-13'
            }, {
                date: '温尼伯',
                name: '加拿大',
                time_jetlag: '-14'
            }, {
                date: '阿比让',
                name: '科特迪瓦',
                time_jetlag: '-8'
            }, {
                date: '亚的斯亚贝巴',
                name: '埃塞俄比亚',
                time_jetlag: '-5'
            }, {
                date: '亚历山大',
                name: '埃及',
                time_jetlag: '-6'
            }, {
                date: '阿尔及尔',
                name: '阿尔及利亚',
                time_jetlag: '-7'
            }, {
                date: '巴马科',
                name: '马里',
                time_jetlag: '-8'
            }, {
                date: '班加西',
                name: '科比亚',
                time_jetlag: '-6'
            }, {
                date: '贝拉',
                name: '莫桑比克',
                time_jetlag: '-6'
            }, {
                date: '布拉柴维尔',
                name: '刚果',
                time_jetlag: '-7'
            }, {
                date: '开罗',
                name: '埃及',
                time_jetlag: '-6'
            }, {
                date: '开普敦',
                name: '南非',
                time_jetlag: '-6'
            }, {
                date: '达喀尔',
                name: '塞内加尔',
                time_jetlag: '-8'
            }, {
                date: '达尔贝达（卡萨布兰卡）',
                name: '摩洛哥',
                time_jetlag: '-8'
            }, {
                date: '达累斯萨拉姆',
                name: '坦桑尼亚',
                time_jetlag: '-5'
            }, {
                date: '吉布提',
                name: '吉布提',
                time_jetlag: '-5'
            }, {
                date: '杜阿拉',
                name: '喀麦隆',
                time_jetlag: '-7'
            }, {
                date: '德班',
                name: '南非',
                time_jetlag: '-6'
            }, {
                date: '哈博罗内',
                name: '博茨瓦纳',
                time_jetlag: '-6'
            }, {
                date: '约翰内斯堡',
                name: '南非',
                time_jetlag: '-6'
            }, {
                date: '坎帕拉',
                name: '乌干达',
                time_jetlag: '-5'
            }, {
                date: '卡诺',
                name: '尼日利亚',
                time_jetlag: '-7'
            }, {
                date: '喀土穆',
                name: '苏丹',
                time_jetlag: '-6'
            }, {
                date: '朱丹',
                name: '南苏丹',
                time_jetlag: '-6'
            }, {
                date: '金沙萨',
                name: '民主刚果',
                time_jetlag: '-7'
            }, {
                date: '拉各斯',
                name: '尼日利亚',
                time_jetlag: '-7'
            }, {
                date: '拉斯帕尔马斯',
                name: '加那利群岛',
                time_jetlag: '-8'
            }, {
                date: '罗安达',
                name: '安哥拉',
                time_jetlag: '-7'
            }, {
                date: '卢萨卡',
                name: '赞比亚',
                time_jetlag: '-6'
            }, {
                date: '马普托',
                name: '莫桑比克',
                time_jetlag: '-6'
            }, {
                date: '摩加迪沙',
                name: '索马里',
                time_jetlag: '-5'
            }, {
                date: '蒙巴萨',
                name: '肯尼亚',
                time_jetlag: '-5'
            }, {
                date: '蒙罗维亚',
                name: '利比里亚',
                time_jetlag: '-8'
            }, {
                date: '内罗毕',
                name: '肯尼亚',
                time_jetlag: '-5'
            }, {
                date: '恩贾梅纳',
                name: '乍得',
                time_jetlag: '-7'
            }, {
                date: '尼亚美',
                name: '尼日尔',
                time_jetlag: '-8'
            }, {
                date: '努瓦克肖特',
                name: '毛里塔尼亚',
                time_jetlag: '-8'
            }, {
                date: '黑角',
                name: '刚果',
                time_jetlag: '-7'
            }, {
                date: '路易港',
                name: '毛里求斯',
                time_jetlag: '-4'
            }, {
                date: '比勒陀利亚',
                name: '南非',
                time_jetlag: '-6'
            }, {
                date: '拉比特',
                name: '摩洛哥',
                time_jetlag: '-8'
            }, {
                date: '圣多美',
                name: '圣多美和普林西比',
                time_jetlag: '-8'
            }, {
                date: '塔那那利佛',
                name: '马达加斯加',
                time_jetlag: '-5'
            }, {
                date: '的黎波里',
                name: '利比亚',
                time_jetlag: '-6'
            }, {
                date: '突尼斯',
                name: '突尼斯',
                time_jetlag: '-7'
            }, {
                date: '温得和克',
                name: '纳米比亚',
                time_jetlag: '-6'
            }, {
                date: '阿加尼亚',
                name: '关岛',
                time_jetlag: '+2'
            }, {
                date: '阿皮亚',
                name: '西萨摩亚',
                time_jetlag: '-19'
            }, {
                date: '奥克兰',
                name: '新西兰',
                time_jetlag: '+4'
            }, {
                date: '布里斯班',
                name: '澳大利亚',
                time_jetlag: '+2'
            }, {
                date: '堪培拉',
                name: '澳大利亚',
                time_jetlag: '+2'
            }, {
                date: '佛里曼特尔',
                name: '澳大利亚',
                time_jetlag: '0'
            }, {
                date: '霍巴特',
                name: '澳大利亚',
                time_jetlag: '+2'
            }, {
                date: '火奴鲁鲁（檀香山）',
                name: '澳大利亚',
                time_jetlag: '-18'
            }, {
                date: '墨尔本',
                name: '澳大利亚',
                time_jetlag: '+2'
            }, {
                date: '努美阿',
                name: '法属新喀里多尼亚',
                time_jetlag: '+3'
            }, {
                date: '帕尼提',
                name: '法属波利尼西亚',
                time_jetlag: '-18'
            }, {
                date: '佩思',
                name: '澳大利亚',
                time_jetlag: '0'
            }, {
                date: '莫尔兹比港',
                name: '巴布亚新几内亚',
                time_jetlag: '+2'
            }, {
                date: '苏瓦',
                name: '斐济',
                time_jetlag: '+4'
            }, {
                date: '悉尼',
                name: '澳大利亚',
                time_jetlag: '+2'
            }, {
                date: '维拉港',
                name: '瓦努阿图',
                time_jetlag: '+3'
            }, {
                date: '惠灵顿',
                name: '新西兰',
                time_jetlag: '+4'
            }
            ],
            search: '',
            pagesize: 8,
            currentPage: 1,
        }
    },
    methods: {
        currentTime() {
            setInterval(this.formatDate, 500)
        },
        formatDate() {
            let date = new Date()
            let year = date.getFullYear() // 年
            let month = date.getMonth() + 1 // 月
            let day = date.getDate() // 日
            let week = date.getDay() // 星期
            let weekArr = ['星期日', '星期一', '星期二', '星期三', '星期四', '星期五', '星期六']
            let hour = date.getHours() // 时
            hour = hour < 10 ? '0' + hour : hour // 如果只有一位，则前面补零
            let minute = date.getMinutes() // 分
            minute = minute < 10 ? '0' + minute : minute // 如果只有一位，则前面补零
            let second = date.getSeconds() // 秒
            second = second < 10 ? '0' + second : second // 如果只有一位，则前面补零
            this.nowDate = `${year}年${month}月${day}日 ${hour}:${minute}:${second} ${weekArr[week]}`
        },
        searchResource() {
            this.currentPage = 1; //将当前页设置为1，确保每次都是从第一页开始搜
            let filterKeywords = this.search.trim();
            let filerReasource = this.tableData.filter(item => { //过滤全部数据
                if (item.name.includes(filterKeywords)) {
                    return item
                }
            })
            this.filterDataShow = filerReasource; //将符合条件的内容赋给filterDataShow
        },
        onSubmit() { },
        handleSizeChange(psize) {
            this.pagesize = psize;
        },
        handleCurrentChange(currentPage) {
            this.currentPage = currentPage;
        }
    },
    mounted(){
        this.currentTime();
        this.searchResource();
    },
    watch: { //监听搜索框内容，当搜索框内容发生变化时调用searchResource方法
        search: {
            handler() {
                this.searchResource();
            }
        }

    },
    computed: {
        //showTable计算属性通过slice方法计算表格当前应显示的数据
        showTable() {
            return this.filterDataShow.slice(
                (this.currentPage - 1) * this.pagesize,
                this.currentPage * this.pagesize
            );
        }
    },
    // 销毁定时器
    beforeDestroy() {
    if (this.formatDate) {
        clearInterval(this.formatDate); // 在Vue实例销毁前，清除时间定时器
    }
    }
})
