//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFlightManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AIRLINE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AIRLINE()
        {
            this.FLIGHT = new HashSet<FLIGHT>();
        }
    
        public int AIRLINE_ID { get; set; }
        public Nullable<int> MILEAGE { get; set; }
        public string AIRLINE_NAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FLIGHT> FLIGHT { get; set; }
        public virtual DEPARTS DEPARTS { get; set; }
        public virtual ARRIVES ARRIVES { get; set; }
    }
}
