//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFlightManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FEEDBACK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FEEDBACK()
        {
            this.FEEDBACK_ANSWER = new HashSet<FEEDBACK_ANSWER>();
        }
    
        public string USER_ID { get; set; }
        public string FEEDBACK_ID { get; set; }
        public Nullable<System.DateTime> FEEDBACK_TIME { get; set; }
        public string FEEDBACK_CONTENT { get; set; }
    
        public virtual USER_ACCOUNT USER_ACCOUNT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FEEDBACK_ANSWER> FEEDBACK_ANSWER { get; set; }
    }
}
