//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFlightManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FEEDBACK_ANSWER
    {
        public string ADMIN_ID { get; set; }
        public string FEEDBACK_ID { get; set; }
        public string DEALT_ID { get; set; }
        public string ANSWER_CONTENT { get; set; }
        public Nullable<System.DateTime> ANSWER_TIME { get; set; }
    
        public virtual ADMIN_ACCOUNT ADMIN_ACCOUNT { get; set; }
        public virtual FEEDBACK FEEDBACK { get; set; }
    }
}
