//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFlightManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLIGHT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FLIGHT()
        {
            this.PLANE_TICKET = new HashSet<PLANE_TICKET>();
        }
    
        public string FLIGHT_NUMBER { get; set; }
        public Nullable<int> AIRPLANE_ID { get; set; }
        public System.DateTime DEPART_DATE { get; set; }
        public Nullable<System.DateTime> ARRIVE_DATE { get; set; }
        public string FLIGHT_STATE { get; set; }
        public Nullable<int> AIRLINE_ID { get; set; }
        public string COMPANY_NAME { get; set; }
        public Nullable<int> FIRST_CLASS_PRICE { get; set; }
        public Nullable<int> ECONOMY_CLASS_PRICE { get; set; }
    
        public virtual AIRLINE AIRLINE { get; set; }
        public virtual AIRPLANE AIRPLANE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLANE_TICKET> PLANE_TICKET { get; set; }
    }
}
