//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFlightManager.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADMIN_ACCOUNT> ADMIN_ACCOUNT { get; set; }
        public virtual DbSet<AIRLINE> AIRLINE { get; set; }
        public virtual DbSet<AIRLINE_COMPANY> AIRLINE_COMPANY { get; set; }
        public virtual DbSet<AIRPLANE> AIRPLANE { get; set; }
        public virtual DbSet<AIRPORT> AIRPORT { get; set; }
        public virtual DbSet<ARRIVES> ARRIVES { get; set; }
        public virtual DbSet<CANCELS> CANCELS { get; set; }
        public virtual DbSet<CHANGES> CHANGES { get; set; }
        public virtual DbSet<CITY> CITY { get; set; }
        public virtual DbSet<DEPARTS> DEPARTS { get; set; }
        public virtual DbSet<FEEDBACK> FEEDBACK { get; set; }
        public virtual DbSet<FEEDBACK_ANSWER> FEEDBACK_ANSWER { get; set; }
        public virtual DbSet<FLIGHT> FLIGHT { get; set; }
        public virtual DbSet<MESSAGE> MESSAGE { get; set; }
        public virtual DbSet<PLANE_TICKET> PLANE_TICKET { get; set; }
        public virtual DbSet<PURCHASES> PURCHASES { get; set; }
        public virtual DbSet<SEAT> SEAT { get; set; }
        public virtual DbSet<TIME_DIFFERENCE> TIME_DIFFERENCE { get; set; }
        public virtual DbSet<USER_ACCOUNT> USER_ACCOUNT { get; set; }
        public virtual DbSet<USER_SEAT> USER_SEAT { get; set; }
    }
}
