//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFlightManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEAT
    {
        public int AIRPLANE_ID { get; set; }
        public string FLIGHT_CLASS { get; set; }
        public Nullable<byte> ROW_SUM { get; set; }
        public Nullable<byte> COLUMN_SUM { get; set; }
    
        public virtual AIRPLANE AIRPLANE { get; set; }
    }
}
